/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project1_fees_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;

/**
 *
 * @author nehap
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }
    int id = 0;
    int getid()
    {
        ResultSet rs = null;
         try
                {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String url = "jdbc:mysql://localhost:3306/feesmsdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL ";
                    Connection con=DriverManager.getConnection(url, "root", "oracle");
                    String sql="select max(id) from signup";
                    Statement st=con.createStatement();
                    rs=st.executeQuery(sql);
                    while(rs.next())
                    {
                        id=rs.getInt(1);
                        id++;

                    }
                }
         catch(Exception e)
         {
            e.printStackTrace();
         }
         return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtdob = new com.toedter.calendar.JDateChooser();
        jTextLast = new javax.swing.JTextField();
        jTextUser = new javax.swing.JTextField();
        jTextContact = new javax.swing.JTextField();
        jTextFirst = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9error = new javax.swing.JLabel();
        jLabel10Contact = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Confirm ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 140, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Contact");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 140, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("D.O.B.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 140, 40));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 220, 30));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 220, 30));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 220, 30));

        jTextLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastActionPerformed(evt);
            }
        });
        getContentPane().add(jTextLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 220, 30));

        jTextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 220, 30));

        jTextContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContactActionPerformed(evt);
            }
        });
        jTextContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextContactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextContactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContactKeyTyped(evt);
            }
        });
        getContentPane().add(jTextContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 220, 30));
        getContentPane().add(jTextFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 220, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 110, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 110, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 110, 30));

        jLabel9error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9error.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel9error, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 250, 30));

        jLabel10Contact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10Contact.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel10Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 240, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastActionPerformed

    private void jTextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserActionPerformed

    private void jTextContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContactActionPerformed

    }//GEN-LAST:event_jTextContactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             validation();
             if(validation())
             {
                 insertData();
             }else
             {
                  JOptionPane.showMessageDialog(this,"validation issue.");
             }
                
             Signup s1 = new Signup();
             s1.show();
             this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
       passwordCheck();
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        passwordCheck();
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
          passwordCheck();
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

    }//GEN-LAST:event_jButton2KeyPressed

    private void jTextContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContactKeyPressed
       contactCheck();
    }//GEN-LAST:event_jTextContactKeyPressed

    private void jTextContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContactKeyReleased
        contactCheck();
    }//GEN-LAST:event_jTextContactKeyReleased

    private void jTextContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContactKeyTyped
         contactCheck();
    }//GEN-LAST:event_jTextContactKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
login l1 = new login();
l1.show();
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
               jTextFirst.setText("");
               jTextLast.setText("");
               jTextUser.setText("");
               jPasswordField1.setText("");
               jPasswordField2.setText("");
               jTextContact.setText("");
//               txtdob.getDate();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    String fname,lname,uname,password,cpassword,cnumber;
             Date dob;
             
             void insertData()
             {
                 SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
                 String dob1=s1.format(dob);
                try
                {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String url = "jdbc:mysql://localhost:3306/feesmsdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL ";
                    Connection con=DriverManager.getConnection(url, "root", "oracle");
                    
                    String sql = "insert into signup values(?,?,?,?,?,?,?)";
                    PreparedStatement st = con.prepareStatement(sql);
                    st.setInt(1, getid());
                    st.setString(2, fname);
                    st.setString(3, lname);
                    st.setString(4, uname);
                    st.setString(5, password);
                    st.setString(6, dob1);
                    st.setString(7, cnumber);
                   int i =st.executeUpdate();
                   if(i>0)
                   {
                       JOptionPane.showMessageDialog(this, "Record inserted successfully");
                   }
                   else
                   {
                     JOptionPane.showMessageDialog(this, "Record not inserted successfully");  
                   }
                   
                }
                catch(Exception e)
                {
            e.printStackTrace();
                } 
                
             }
             
             boolean validation()
             {
               fname =  jTextFirst.getText();
               lname =  jTextLast.getText();
               uname =  jTextUser.getText();
               password =  jPasswordField1.getText();
               cpassword =  jPasswordField2.getText();
               cnumber =  jTextContact.getText();
               dob =  txtdob.getDate();
               
               if(fname.equals(""))
               {
                   JOptionPane.showMessageDialog(this,"Please! enter your first name");
                   return false;
               }
                if(lname.equals(""))
               {
                   JOptionPane.showMessageDialog(this,"Please! enter your last name");
                   return false;
               }
                 if(uname.equals(""))
               {
                   JOptionPane.showMessageDialog(this,"Please! enter your username" );
                   return false;
               }
                  if(password.equals(""))
               {
                   JOptionPane.showMessageDialog(this,"Please! enter your password");
                   return false;
               }
                   if(cpassword.equals(""))
               {
                   JOptionPane.showMessageDialog(this,"Please! Confirm your password");
                   return false;
               }
                    if(cnumber.equals(""))
               {
                   JOptionPane.showMessageDialog(this,"Please! enter your contact number");
                   return false;
               }
                     if(dob == null)
               {
                   JOptionPane.showMessageDialog(this,"Please! enter your DateOfBirth");
                   return false;
               }
                     return true;
             }
        void passwordCheck()
        {
           password =  jPasswordField1.getText();
           if(password.length()>=8)
           {
               jLabel9error.setText("");
           }
           else
           {
               jLabel9error.setText("Enter 8 digit password");
           }
        }
        
        void contactCheck()
        {
              cnumber =  jTextContact.getText();
              if(cnumber.length()==10)
              {
                   jLabel10Contact.setText("");
              }
              else
              {
                 jLabel10Contact.setText("Enter 10 digit conatact number");
              }
        }
             
             
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10Contact;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9error;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextContact;
    private javax.swing.JTextField jTextFirst;
    private javax.swing.JTextField jTextLast;
    private javax.swing.JTextField jTextUser;
    private com.toedter.calendar.JDateChooser txtdob;
    // End of variables declaration//GEN-END:variables

    private int getId() {
        return id; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
